version: '3'
services:
  fluentd:
    build: .
    container_name: fluentd
    volumes:
      - ./conf:/fluentd/etc # 로컬의 fluentd.conf 파일을 컨테이너로 마운트
      - /var/log/nginx/oauth2client:/var/log
      - /var/lib/docker/containers:/fluentd/log/containers
    ports:
      - "5140:5140/udp"
      - "24224:24224"
      - "24224:24224/udp"
