---
- name: 'restart-docker-fluent'
  become: yes
  docker_container:
    image: "fluent/fluentd:{{ docker_tag }}"
    name: "{{ container_name }}"
    volumes: '{{ exposed_volumes }}'
    ports: '{{ published_ports }}'
    exposed_ports: '{{ exposed_ports }}'
    networks:
      - name: '{{ docker_network }}'
    state: 'stopped'
    restart_policy: 'no'
    # log_driver: 'syslog'
    # log_opt:
    #   tag: "{{ container_name}}"
  notify: 'start-docker-fluent'
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: 'start-docker-fluent'
  become: yes
  docker_container:
    image: "fluent/fluentd:{{ docker_tag }}"
    name: "{{ container_name }}"
    volumes: '{{ exposed_volumes }}'
    ports: '{{ published_ports }}'
    exposed_ports: '{{ exposed_ports }}'
    networks:
      - name: '{{ docker_network }}'
    state: 'started'
    restart_policy: 'no'
    # log_driver: 'syslog'
    # log_opt:
    #   tag: "{{ container_name }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3

# restart for syslog
- name: 'Restart rsyslog'
  service:
    name: rsyslog
    state: restarted
  when: service_default_state | default('started') == 'started'
