---
- include: multi_os.yml

- include_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'

- name: "{{ base_directory }} 디렉토리 생성"
  file:
    path: "{{ base_directory }}"
    state: 'directory'
    mode: '0755'

- name: "{{ config_directory }} 디렉토리 생성"
  file:
    path: "{{ config_directory }}"
    state: 'directory'
    mode: '0755'

# template
- name: "도커 파일을 {{ base_directory }}에 복사"
  template:
    src: Dockerfile.js
    dest: "{{ base_directory }}/Dockerfile"

- name: 도커 컨테이너 이미지 빌드
  docker_image:
    name: "fluent/fluentd:{{ docker_tag }}"
    build:
      path: "{{ base_directory }}"
      source: build
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3

# app template
- name: "{{ config_file_name }} 템플릿을 {{ config_directory }}로 복사"
  template:
    src: "{{ config_file_name }}"
    dest: "{{ config_directory }}/fluent.conf"
  notify: 'restart-docker-fluent'

#### Start docker container
- name: 'Fluent 컨테이너 스타트'
  docker_container:
    image: "fluent/fluentd:{{ docker_tag }}"
    name: "{{ container_name }}"
    volumes: '{{ exposed_volumes }}'
    ports: '{{ published_ports }}'
    exposed_ports: '{{ exposed_ports }}'
    networks:
      - name: '{{ docker_network_name  }}'  
    state: 'started'
    restart_policy: 'no'
  vars:
    ansible_python_interpreter: /usr/bin/python3
