---

- include: multi_os.yml

- include_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'

- name: "Create the {{ base_directory }} directory on the host"
  file:
    path: "{{ base_directory }}"
    state: 'directory'
    mode: '0755'

- name: "Create the {{ config_directory }} directory on the host"
  file:
    path: "{{ config_directory }}"
    state: 'directory'
    mode: '0755'
#### syslog begin // 맞는 json 포맷을 찾아야 함
# - name: "Copy syslog file : 01-json-template.conf"
#   template:
#     src: Dockerfile.js
#     dest: "{{ syslog_dir }}/01-json-template.conf"

- name: "Copy syslog file : 70-outpout.conf"
  template:
    src: 70-outpout.conf
    dest: "{{ syslog_dir }}/70-outpout.conf"
  notify: 'Restart rsyslog'
#### syslog end
- name: "Copy Docker file in to the {{ base_directory }}"
  template:
    src: Dockerfile.js
    dest: "{{ base_directory }}/Dockerfile"

- name: build container image
  docker_image:
    name: "fluent/fluentd:{{ docker_tag }}"
    build:
      path: "{{ base_directory }}"
      source: build
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: "Put the {{ config_file_name }} file in {{ config_directory }}"
  template:
    src: syslog.fluent.conf.js
    dest: "{{ config_directory }}/fluent.conf"
  notify: 'restart-docker-fluent'
#### Start docker container
- name: 'Start the fluent docker container'
  docker_container:
    image: "fluent/fluentd:{{ docker_tag }}"
    name: "{{ container_name }}"
    volumes: '{{ exposed_volumes }}'
    ports: '{{ published_ports }}'
    exposed_ports: '{{ exposed_ports }}'
    state: 'started'
    restart_policy: 'no'
    log_driver: 'syslog'
    log_options:
      tag: "{{ container_name }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
