---
app__log_directory: "/home/azureuser/log"
base_directory: "/home/azureuser/fluent"
config_file_name: "fluent.conf"
config_directory: "{{ base_directory }}/conf"
log_diectory: /var/log
container_name: 'fluent'
docker_tag: 'v1.12.0-debian-1.0'

exposed_ports:
  - "5140"
  - "24224"
  - "24224/udp"

published_ports:
  - "5140:5140/udp"
  - "24224:24224"
  - "24224:24224/udp"

exposed_volumes:
  - /etc/localtime:/etc/localtime:ro
  - "{{ config_directory }}:/fluentd/etc" # 로컬의 fluentd.conf 파일을 컨테이너로 마운트
  - "{{ app__log_directory }}:{{ log_diectory }}" # 모니터링 대상 로그 디렉토리
